name: Deploy Static Site

on:
  push:
    branches:
      - main  # Voer deze workflow alleen uit bij pushes naar de 'main' branch

permissions:
  contents: write  # Nodig voor pushen naar GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml markdown Jinja2

    - name: Build the static site
      run: |
        python main.py  # Voer jouw script uit om de site te genereren

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Geef hier de map aan waar jouw site wordt gegenereerd
